# Generated by Django 5.0.3 on 2024-03-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='zip_file',
            field=models.FileField(blank=True, upload_to='project_zip_files/'),
        ),
    ]
